version: "3.1"
services:

  scheduler:
    networks:
      - airflow

  datawarehouse-db:
    image: postgres:17
    container_name: datawarehouse-db
    env_file:
      - .env.local
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - airflow

  datawarehouse-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: datawarehouse-pgadmin
    env_file:
      - .env.local
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - datawarehouse-db
    networks:
      - airflow

  minio-datalake:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: minio-datalake
    hostname: minio-datalake
    restart: always
    volumes:
      - ./data/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env.local
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - airflow

networks:
  airflow:
    driver: bridge
