#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
-- Create DEV database and schemas
CREATE DATABASE "DB_SR_DEV";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "DB_SR_DEV" <<-EOSQL
CREATE SCHEMA IF NOT EXISTS "STAGING";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
-- Create PRD database and schemas
CREATE DATABASE "DB_SR_PRD";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "DB_SR_PRD" <<-EOSQL
CREATE SCHEMA IF NOT EXISTS "STAGING";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
-- Create a dedicated user for the application
CREATE USER ${AIRFLOW_DB_USER} WITH PASSWORD '${AIRFLOW_DB_PASSWORD}';

-- Grant database connection permissions
GRANT CONNECT ON DATABASE "DB_SR_DEV" TO ${AIRFLOW_DB_USER};
GRANT CONNECT ON DATABASE "DB_SR_PRD" TO ${AIRFLOW_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "DB_SR_DEV" <<-EOSQL
GRANT USAGE, CREATE ON SCHEMA "STAGING" TO ${AIRFLOW_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "DB_SR_PRD" <<-EOSQL
GRANT USAGE, CREATE ON SCHEMA "STAGING" TO ${AIRFLOW_DB_USER};
EOSQL
